# exceptionally reinstate python 3.7 support, to be removed
# at any time, but ideally once upstream drops support itself
python:
  - 3.7.* *_cpython
  - 3.8.* *_cpython
  - 3.9.* *_cpython
  - 3.10.* *_cpython
  - 3.11.* *_cpython
  - 3.6.* *_73_pypy    # [not (osx and arm64)]
  - 3.7.* *_73_pypy    # [not (osx and arm64)]
  - 3.8.* *_73_pypy    # [not (osx and arm64)]
  - 3.9.* *_73_pypy    # [not (osx and arm64)]
python_impl:
  - cpython
  - cpython
  - cpython
  - cpython
  - cpython
  - pypy               # [not (osx and arm64)]
  - pypy               # [not (osx and arm64)]
  - pypy               # [not (osx and arm64)]
  - pypy               # [not (osx and arm64)]
numpy:
  - 1.20
  - 1.21
  - 1.21
  - 1.21
  - 1.23
  - 1.20               # [not (osx and arm64)]
  - 1.20               # [not (osx and arm64)]
  - 1.21               # [not (osx and arm64)]
  - 1.21               # [not (osx and arm64)]
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86]
  - '10.12'                # [osx and x86]
